# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' This is stuff
#'
#' @return nothing
#' @export
init <- function() {
    invisible(.Call('_Rmmquant_init', PACKAGE = 'Rmmquant'))
}

printUsage <- function() {
    invisible(.Call('_Rmmquant_printUsage', PACKAGE = 'Rmmquant'))
}

printState <- function() {
    invisible(.Call('_Rmmquant_printState', PACKAGE = 'Rmmquant'))
}

setGtfFileName <- function(s) {
    invisible(.Call('_Rmmquant_setGtfFileName', PACKAGE = 'Rmmquant', s))
}

addReadsFileName <- function(s) {
    invisible(.Call('_Rmmquant_addReadsFileName', PACKAGE = 'Rmmquant', s))
}

addName <- function(s) {
    invisible(.Call('_Rmmquant_addName', PACKAGE = 'Rmmquant', s))
}

setOutputFileName <- function(s) {
    invisible(.Call('_Rmmquant_setOutputFileName', PACKAGE = 'Rmmquant', s))
}

setOverlap <- function(f) {
    invisible(.Call('_Rmmquant_setOverlap', PACKAGE = 'Rmmquant', f))
}

addStrand <- function(s) {
    .Call('_Rmmquant_addStrand', PACKAGE = 'Rmmquant', s)
}

addSort <- function(s) {
    .Call('_Rmmquant_addSort', PACKAGE = 'Rmmquant', s)
}

setCountThreshold <- function(u) {
    invisible(.Call('_Rmmquant_setCountThreshold', PACKAGE = 'Rmmquant', u))
}

setMergeThreshold <- function(f) {
    invisible(.Call('_Rmmquant_setMergeThreshold', PACKAGE = 'Rmmquant', f))
}

setPrintGeneName <- function(b) {
    invisible(.Call('_Rmmquant_setPrintGeneName', PACKAGE = 'Rmmquant', b))
}

setFeatureCountStyle <- function(b) {
    invisible(.Call('_Rmmquant_setFeatureCountStyle', PACKAGE = 'Rmmquant', b))
}

setProgress <- function(b) {
    invisible(.Call('_Rmmquant_setProgress', PACKAGE = 'Rmmquant', b))
}

setNThreads <- function(n) {
    invisible(.Call('_Rmmquant_setNThreads', PACKAGE = 'Rmmquant', n))
}

addFormat <- function(s) {
    .Call('_Rmmquant_addFormat', PACKAGE = 'Rmmquant', s)
}

setNOverlapDifference <- function(n) {
    invisible(.Call('_Rmmquant_setNOverlapDifference', PACKAGE = 'Rmmquant', n))
}

setPcOverlapDifference <- function(f) {
    invisible(.Call('_Rmmquant_setPcOverlapDifference', PACKAGE = 'Rmmquant', f))
}

start <- function() {
    .Call('_Rmmquant_start', PACKAGE = 'Rmmquant')
}

